### ISSUE TITLE
it can not be installed on windows computer

### ISSUE THREAD

**Issue by Sandy4321** [scikit-learn-contrib/polylearn#12]
pls see error mesage
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

e:\factirizatoin machine including FFM\code\polylearn_master_June6>python setup.py build
Appending polylearn.tests configuration to polylearn
Ignoring attempt to set 'name' (from 'polylearn' to 'polylearn.tests')
Appending polylearn configuration to
Ignoring attempt to set 'name' (from '' to 'polylearn')
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "polylearn.loss_fast" sources
building extension "polylearn.cd_direct_fast" sources
building extension "polylearn.cd_linear_fast" sources
building extension "polylearn.cd_lifted_fast" sources
build_src: building npy-pkg config files
running build_py
creating build
creating build\lib.win-amd64-3.5
creating build\lib.win-amd64-3.5\polylearn
copying polylearn\base.py -> build\lib.win-amd64-3.5\polylearn
copying polylearn\factorization_machine.py -> build\lib.win-amd64-3.5\polylearn
copying polylearn\kernels.py -> build\lib.win-amd64-3.5\polylearn
copying polylearn\loss.py -> build\lib.win-amd64-3.5\polylearn
copying polylearn\polynomial_network.py -> build\lib.win-amd64-3.5\polylearn
copying polylearn\setup.py -> build\lib.win-amd64-3.5\polylearn
copying polylearn\__init__.py -> build\lib.win-amd64-3.5\polylearn
creating build\lib.win-amd64-3.5\polylearn\tests
copying polylearn\tests\test_cd_linear.py -> build\lib.win-amd64-3.5\polylearn\tests
copying polylearn\tests\test_common.py -> build\lib.win-amd64-3.5\polylearn\tests
copying polylearn\tests\test_factorization_machine.py -> build\lib.win-amd64-3.5\polylearn\tests
copying polylearn\tests\test_kernels.py -> build\lib.win-amd64-3.5\polylearn\tests
copying polylearn\tests\test_polynomial_network.py -> build\lib.win-amd64-3.5\polylearn\tests
copying polylearn\tests\__init__.py -> build\lib.win-amd64-3.5\polylearn\tests
running build_ext
Warning: Assuming default configuration (polylearn\tests/{setup_tests,setup}.py was not found)Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    'Operating System :: MacOS'
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\core.py", line 166, in setup
    return old_setup(**new_attr)
  File "C:\Users\cde3\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\cde3\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\cde3\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\command\build.py", line 47, in run
    old_build.run(self)
  File "C:\Users\cde3\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\cde3\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cde3\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\command\build_ext.py", line 117, in run
    force=self.force)
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 596, in new_compiler
    compiler = klass(None, dry_run, force)
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 58, in __init__
    dry_run, force)
  File "C:\Users\cde3\Anaconda3\lib\distutils\cygwinccompiler.py", line 157, in __init__
    self.dll_libraries = get_msvcr()
  File "C:\Users\cde3\Anaconda3\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
    raise ValueError("Unknown MS Compiler version %s " % msc_ver)
ValueError: Unknown MS Compiler version 1900

e:\factirizatoin machine including FFM\code\polylearn_master_June6>python setup.py install
Appending polylearn.tests configuration to polylearn
Ignoring attempt to set 'name' (from 'polylearn' to 'polylearn.tests')
Appending polylearn configuration to
Ignoring attempt to set 'name' (from '' to 'polylearn')
running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "polylearn.loss_fast" sources
building extension "polylearn.cd_direct_fast" sources
building extension "polylearn.cd_linear_fast" sources
building extension "polylearn.cd_lifted_fast" sources
build_src: building npy-pkg config files
creating polylearn.egg-info
writing dependency_links to polylearn.egg-info\dependency_links.txt
writing polylearn.egg-info\PKG-INFO
writing top-level names to polylearn.egg-info\top_level.txt
writing manifest file 'polylearn.egg-info\SOURCES.txt'
reading manifest file 'polylearn.egg-info\SOURCES.txt'
writing manifest file 'polylearn.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Warning: Assuming default configuration (polylearn\tests/{setup_tests,setup}.py was not found)Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    'Operating System :: MacOS'
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\core.py", line 166, in setup
    return old_setup(**new_attr)
  File "C:\Users\cde3\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\cde3\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\cde3\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\command\install.py", line 62, in run
    r = self.setuptools_run()
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\command\install.py", line 56, in setuptools_run
    self.do_egg_install()
  File "C:\Users\cde3\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\command\install.py", line 109, in do_egg_install
  File "C:\Users\cde3\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cde3\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cde3\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\command\bdist_egg.py", line 161, in run
  File "C:\Users\cde3\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\command\bdist_egg.py", line 147, in call_command
  File "C:\Users\cde3\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cde3\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cde3\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\command\install_lib.py", line 11, in run
  File "C:\Users\cde3\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\cde3\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cde3\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\command\build_ext.py", line 117, in run
    force=self.force)
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 596, in new_compiler
    compiler = klass(None, dry_run, force)
  File "C:\Users\cde3\Anaconda3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 58, in __init__
    dry_run, force)
  File "C:\Users\cde3\Anaconda3\lib\distutils\cygwinccompiler.py", line 157, in __init__
    self.dll_libraries = get_msvcr()
  File "C:\Users\cde3\Anaconda3\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
    raise ValueError("Unknown MS Compiler version %s " % msc_ver)
ValueError: Unknown MS Compiler version 1900

e:\factirizatoin machine including FFM\code\polylearn_master_June6>

**Comment by vene** [comment]
Polylearn is built and tested on windows via appveyor, and the library builds successfully, as you can see in the log [here](https://ci.appveyor.com/project/vene/polylearn/build/job/48ulj1u1d3vq3jfq), for instance. For a quick fix, you can try to go to the "Artifacts" tab of that page, and download the binary wheel or exe installer from there, and just install that.

Your issue seems to be not with polylearn in particular, but with building cython extensions in general. You might want to take a look at [this page on the Cython wiki](https://github.com/cython/cython/wiki/CythonExtensionsOnWindows).

Finally, you can also look at how the [appveyor config script](https://github.com/scikit-learn-contrib/polylearn/blob/master/appveyor.yml#L41) that we are using sets up the windows build. In particular, note that it removes cygwin, and it installs a specific older version of setuptools. This might be necessary in your case as well.

Hope this helps!

**Comment by vene** [comment]
Try downloading [this auto-generated installer from appveyor](https://ci.appveyor.com/api/buildjobs/48ulj1u1d3vq3jfq/artifacts/dist%2Fpolylearn-0.1.dev0.win-amd64-py3.5.exe) and let me know if it works.

**Comment by Sandy4321** [comment]
this link 
Try downloading this auto-generated installer from appveyor and let me know if it works.
is not working 
may you kindly reload it?

**Comment by Sandy4321** [comment]
may help to find
For a quick fix, you can try to go to the "Artifacts" tab of that page,
from this link?
https://ci.appveyor.com/project/vene/polylearn/build/job/48ulj1u1d3vq3jfq

**Comment by vene** [comment]
As that page says, artifacts get deleted after 6 months, which is why you can't find them anymore. Like I said before, it looks like you should disable cygwin and install the correct visual c++ compiler for your python version. It might work to use a distutils.cfg file, see here for more info: https://wiki.python.org/moin/WindowsCompilers
